language: node_js
arch:
  - amd64
  - ppc64le
os:
  - linux
  - windows
sudo: false
node_js:
  - "14"
  - "12"
  - "10"
  - "8"
jobs:
  exclude:
  - arch: ppc64le
    os: windows
after_success:
  - npm run codecov
